import { NextRequest } from "next/server";
import { cleanText } from "@/lib/live-meeting";
import { isAuthContext, requireAuth } from "@/lib/server-auth";

const fields = "id,name,category,severity,status,camera_id,zone_id,conditions,notification_config,hse_workflow_config,created_by,updated_by,created_at,updated_at";
const categories = ["ppe", "restricted_zone", "equipment", "behavioral", "fire_smoke", "people_vehicle", "proximity"];
const severities = ["low", "medium", "high", "critical"];

export async function GET(request: NextRequest) { const auth = await requireAuth(request); if (!isAuthContext(auth)) return auth; const { data, error } = await auth.client.from("vision_rules").select(fields).order("created_at", { ascending: false }).limit(200); if (error) return Response.json({ ok: false, error: error.message }, { status: 500 }); return Response.json({ ok: true, data: data ?? [] }); }
export async function POST(request: NextRequest) { const auth = await requireAuth(request); if (!isAuthContext(auth)) return auth; if (!auth.isStaff) return Response.json({ ok: false, error: "Vision rule management requires HSE staff access." }, { status: 403 }); const body = await request.json().catch(() => null) as Record<string, unknown> | null; const name = cleanText(body?.name, 160); const category = cleanText(body?.category, 40); if (!name || !categories.includes(category) || !severities.includes(String(body?.severity))) return Response.json({ ok: false, error: "Rule name, category, and severity are required." }, { status: 422 }); const { data, error } = await auth.client.from("vision_rules").insert({ name, category, severity: body?.severity, status: body?.status === "inactive" ? "inactive" : "active", camera_id: cleanText(body?.camera_id, 80) || null, zone_id: cleanText(body?.zone_id, 80) || null, conditions: body?.conditions ?? {}, notification_config: body?.notification_config ?? {}, hse_workflow_config: body?.hse_workflow_config ?? {}, created_by: auth.user.id, updated_by: auth.user.id }).select(fields).single(); if (error || !data) return Response.json({ ok: false, error: error?.message ?? "Rule could not be created." }, { status: 422 }); return Response.json({ ok: true, data }, { status: 201 }); }
export async function PATCH(request: NextRequest) { const auth = await requireAuth(request); if (!isAuthContext(auth)) return auth; if (!auth.isStaff) return Response.json({ ok: false, error: "Vision rule management requires HSE staff access." }, { status: 403 }); const body = await request.json().catch(() => null) as Record<string, unknown> | null; const id = cleanText(body?.id, 80); if (!id) return Response.json({ ok: false, error: "Rule ID is required." }, { status: 422 }); const { data, error } = await auth.client.from("vision_rules").update({ name: cleanText(body?.name, 160), category: cleanText(body?.category, 40), severity: body?.severity, status: body?.status, camera_id: cleanText(body?.camera_id, 80) || null, zone_id: cleanText(body?.zone_id, 80) || null, conditions: body?.conditions ?? {}, notification_config: body?.notification_config ?? {}, hse_workflow_config: body?.hse_workflow_config ?? {}, updated_by: auth.user.id, updated_at: new Date().toISOString() }).eq("id", id).select(fields).single(); if (error || !data) return Response.json({ ok: false, error: error?.message ?? "Rule could not be updated." }, { status: 422 }); return Response.json({ ok: true, data }); }
export async function DELETE(request: NextRequest) { const auth = await requireAuth(request); if (!isAuthContext(auth)) return auth; if (!auth.isStaff) return Response.json({ ok: false, error: "Vision rule management requires HSE staff access." }, { status: 403 }); const id = request.nextUrl.searchParams.get("id"); if (!id) return Response.json({ ok: false, error: "Rule ID is required." }, { status: 422 }); const { error } = await auth.client.from("vision_rules").delete().eq("id", id); if (error) return Response.json({ ok: false, error: error.message }, { status: 422 }); return Response.json({ ok: true, data: { id } }); }
