/* eslint-disable @typescript-eslint/no-explicit-any */
import { NextRequest } from "next/server";
import { cleanText } from "@/lib/live-meeting";
import { isAuthContext, requireAuth } from "@/lib/server-auth";
const tables: Record<string, string> = { licenses: "licenses", trainings: "trainings", attendance: "training_attendance", "equipment-auth": "equipment_authorizations", "training-matrix": "training_matrix", competency: "competency", templates: "official_templates" };
const fields: Record<string, string> = { licenses: "id,reference_no,employee_ref,employee_id,employee_name,license_type,qualification_name,issuer,certificate_number,issue_date,expiry_date,status,evidence_url,notes,created_at,updated_at", trainings: "id,reference_no,title,title_ar,category,trainer,factory,location,starts_at,duration_minutes,objectives,status,created_at,updated_at", attendance: "id,training_id,employee_ref,employee_id,employee_name,attendance_status,certificate_number,certificate_issued_at,created_at,updated_at", "equipment-auth": "id,authorization_no,employee_ref,employee_id,employee_name,category,equipment_name,issuing_authority,issue_date,expiry_date,status,restrictions,evidence_url,created_at,updated_at", "training-matrix": "id,employee_ref,employee_id,employee_name,course_code,course_name,status,qualification_date,expiry_date,evidence_url,notes,created_at,updated_at", competency: "id,reference_no,employee_ref,employee_id,employee_name,department,qualification_name,category,issuer,certificate_number,issue_date,expiry_date,status,linked_license_id,linked_authorization_id,linked_training_matrix_id,evidence_url,notes,created_at,updated_at", templates: "id,template_type,document_no,holder_name,holder_name_ar,employee_id,participant_name,participant_name_ar,title,title_ar,issue_date,expiry_date,photo_url,source_type,source_id,board_name,logo_url,status,created_at,updated_at" };
const allowed = new Set(Object.keys(tables));
const clean = (v: unknown, max = 500) => cleanText(v, max) || null;
const error = (message: string, status = 422) => Response.json({ ok: false, error: message }, { status });
function derive(row: any) { if (!row.expiry_date) return row; const days = Math.ceil((new Date(row.expiry_date).getTime() - Date.now()) / 86400000); const status = days < 0 ? "EXPIRED" : days <= 60 ? "EXPIRING_SOON" : row.status; return { ...row, effective_status: status }; }
function normalizeStatus(body: any, resource: string) { if (body.status) return String(body.status); if (resource === "licenses" || resource === "competency" || resource === "equipment-auth") return body.expiry_date ? "VALID" : "NO_EXPIRY"; if (resource === "training-matrix") return "PENDING"; return undefined; }
export async function GET(request: NextRequest) { const auth = await requireAuth(request); if (!isAuthContext(auth)) return auth; const resource = request.nextUrl.searchParams.get("resource") || "licenses"; if (!allowed.has(resource)) return error("Unsupported competency resource.", 404); const table = tables[resource]; const client = auth.client as any; const { data, error: dbError } = await client.from(table).select(fields[resource]).order(resource === "trainings" ? "starts_at" : "created_at", { ascending: false }).limit(500); if (dbError) return error(dbError.message, 500); let rows = (data || []).map(derive); const q = request.nextUrl.searchParams.get("q")?.toLowerCase(); const status = request.nextUrl.searchParams.get("status"); if (q) rows = rows.filter((r: any) => JSON.stringify(r).toLowerCase().includes(q)); if (status) rows = rows.filter((r: any) => r.status === status || r.effective_status === status); return Response.json({ ok: true, data: rows }); }
export async function POST(request: NextRequest) { const auth = await requireAuth(request); if (!isAuthContext(auth)) return auth; if (!auth.isStaff) return error("Section 07 changes require HSE staff access.", 403); const resource = request.nextUrl.searchParams.get("resource") || "licenses"; if (!allowed.has(resource)) return error("Unsupported competency resource.", 404); const body = await request.json().catch(() => null) as any; const user = auth.user.id; let payload: any = { created_by: user };
 if (resource === "licenses") { if (!clean(body?.employee_id) || !clean(body?.employee_name) || !clean(body?.qualification_name) || !clean(body?.license_type)) return error("Employee, license type, and qualification are required."); payload = { reference_no: clean(body.reference_no) || `LIC-${Date.now()}`, employee_ref: clean(body.employee_ref, 80), employee_id: clean(body.employee_id, 80), employee_name: clean(body.employee_name, 180), license_type: clean(body.license_type, 40), qualification_name: clean(body.qualification_name, 180), issuer: clean(body.issuer, 180), certificate_number: clean(body.certificate_number, 120), issue_date: clean(body.issue_date, 20), expiry_date: clean(body.expiry_date, 20), status: normalizeStatus(body, resource), evidence_url: clean(body.evidence_url, 500), notes: clean(body.notes, 2000), created_by: user }; }
 else if (resource === "trainings") { if (!clean(body?.title) || !clean(body?.starts_at)) return error("Training title and date/time are required."); payload = { reference_no: clean(body.reference_no) || `TRN-${Date.now()}`, title: clean(body.title, 240), title_ar: clean(body.title_ar, 240), category: clean(body.category, 40) || "general_hse", trainer: clean(body.trainer, 180), factory: clean(body.factory, 160), location: clean(body.location, 200), starts_at: body.starts_at, duration_minutes: body.duration_minutes ? Number(body.duration_minutes) : null, objectives: clean(body.objectives, 2000), status: clean(body.status, 30) || "planned", created_by: user }; }
 else if (resource === "attendance") { if (!clean(body?.training_id, 80) || !clean(body?.employee_id) || !clean(body?.employee_name)) return error("Training and participant are required."); payload = { training_id: clean(body.training_id, 80), employee_ref: clean(body.employee_ref, 80), employee_id: clean(body.employee_id, 80), employee_name: clean(body.employee_name, 180), attendance_status: clean(body.attendance_status, 20) || "PRESENT", certificate_number: clean(body.certificate_number, 120) }; }
 else if (resource === "equipment-auth") { if (!clean(body?.employee_id) || !clean(body?.employee_name) || !clean(body?.category)) return error("Employee and authorization category are required."); payload = { authorization_no: clean(body.authorization_no) || `AUTH-${Date.now()}`, employee_ref: clean(body.employee_ref, 80), employee_id: clean(body.employee_id, 80), employee_name: clean(body.employee_name, 180), category: clean(body.category, 50), equipment_name: clean(body.equipment_name, 180), issuing_authority: clean(body.issuing_authority, 180), issue_date: clean(body.issue_date, 20), expiry_date: clean(body.expiry_date, 20), status: normalizeStatus(body, resource), restrictions: clean(body.restrictions, 2000), evidence_url: clean(body.evidence_url, 500), created_by: user }; }
 else if (resource === "training-matrix") { if (!clean(body?.employee_id) || !clean(body?.employee_name) || !clean(body?.course_name)) return error("Employee and course are required."); payload = { employee_ref: clean(body.employee_ref, 80), employee_id: clean(body.employee_id, 80), employee_name: clean(body.employee_name, 180), course_code: clean(body.course_code, 80) || String(body.course_name).toUpperCase(), course_name: clean(body.course_name, 80), status: clean(body.status, 20) || "PENDING", qualification_date: clean(body.qualification_date, 20), expiry_date: clean(body.expiry_date, 20), evidence_url: clean(body.evidence_url, 500), notes: clean(body.notes, 2000), updated_by: user }; }
 else if (resource === "competency") { if (!clean(body?.employee_id) || !clean(body?.employee_name) || !clean(body?.qualification_name) || !clean(body?.category)) return error("Employee, qualification, and category are required."); payload = { reference_no: clean(body.reference_no) || `CMP-${Date.now()}`, employee_ref: clean(body.employee_ref, 80), employee_id: clean(body.employee_id, 80), employee_name: clean(body.employee_name, 180), department: clean(body.department, 160), qualification_name: clean(body.qualification_name, 180), category: clean(body.category, 50), issuer: clean(body.issuer, 180), certificate_number: clean(body.certificate_number, 120), issue_date: clean(body.issue_date, 20), expiry_date: clean(body.expiry_date, 20), status: normalizeStatus(body, resource) || "VALID", linked_license_id: clean(body.linked_license_id, 80), linked_authorization_id: clean(body.linked_authorization_id, 80), linked_training_matrix_id: clean(body.linked_training_matrix_id, 80), evidence_url: clean(body.evidence_url, 500), notes: clean(body.notes, 2000), created_by: user }; }
 else { if (!clean(body?.template_type) || !clean(body?.document_no)) return error("Template type and document number are required."); payload = { ...body, created_by: user }; delete payload.id; }
 const { data, error: dbError } = await (auth.client as any).from(tables[resource]).insert(payload).select(fields[resource]).single(); if (dbError || !data) return error(dbError?.message || "Record could not be created.", dbError?.code === "23505" ? 409 : 422); return Response.json({ ok: true, data: derive(data) }, { status: 201 }); }
export async function PATCH(request: NextRequest) { const auth = await requireAuth(request); if (!isAuthContext(auth)) return auth; if (!auth.isStaff) return error("Section 07 changes require HSE staff access.", 403); const resource = request.nextUrl.searchParams.get("resource") || "licenses"; const body = await request.json().catch(() => null) as any; if (!allowed.has(resource) || !clean(body?.id, 80)) return error("Resource and record ID are required."); const patch = { ...body, updated_at: new Date().toISOString() }; delete patch.id; delete patch.created_by; const { data, error: dbError } = await (auth.client as any).from(tables[resource]).update(patch).eq("id", body.id).select(fields[resource]).single(); if (dbError || !data) return error(dbError?.message || "Record could not be updated."); return Response.json({ ok: true, data: derive(data) }); }
export async function DELETE(request: NextRequest) { const auth = await requireAuth(request); if (!isAuthContext(auth)) return auth; if (!auth.isStaff) return error("Section 07 changes require HSE staff access.", 403); const resource = request.nextUrl.searchParams.get("resource") || "licenses"; const id = request.nextUrl.searchParams.get("id"); if (!allowed.has(resource) || !id) return error("Resource and record ID are required."); const { error: dbError } = await (auth.client as any).from(tables[resource]).delete().eq("id", id); if (dbError) return error(dbError.message, 500); return Response.json({ ok: true, data: { id, deleted: true } }); }
