"use client";
/* eslint-disable @typescript-eslint/no-explicit-any, react-hooks/set-state-in-effect */
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { Activity, Building2, CheckCircle2, Database, LoaderCircle, Plus, RefreshCw, Search, Settings2, ShieldCheck, Users, X } from "lucide-react";
import { supabase } from "@/lib/supabase";

export type AdminSystemView = "users"|"activity"|"plants"|"integrations"|"system-readiness"|"settings";

const views = [
  { id:"users", label:"Users & Roles", resource:"users", title:"Users & Roles" },
  { id:"activity", label:"Activity Log", resource:"activity", title:"Activity Log" },
  { id:"plants", label:"Facilities & Sites", resource:"plants", title:"Facilities & Work Sites" },
  { id:"integrations", label:"Integrations", resource:"integrations", title:"Integrations" },
  { id:"system-readiness", label:"System Readiness", resource:"system-readiness", title:"System Readiness" },
  { id:"settings", label:"Settings", resource:"settings", title:"Enterprise Settings" },
] as const;

async function api(path:string, init?:RequestInit) {
  if (!supabase) throw new Error("Supabase is not configured.");
  const { data } = await supabase.auth.getSession();
  const token = data.session?.access_token;
  if (!token) throw new Error("Your session has expired.");
  const response = await fetch(path,{...init,headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`,...(init?.headers||{})}});
  const raw = await response.text();
  let body:any={};
  try { body = raw ? JSON.parse(raw) : {}; } catch { throw new Error(`API returned a non-JSON response (${response.status}).`); }
  if (!response.ok || body.ok===false) throw new Error(body.error || `Request failed (${response.status})`);
  return body.data;
}
const txt=(v:unknown,f="—")=>v===null||v===undefined||v===""?f:String(v);
const fmt=(v:unknown)=>v?new Intl.DateTimeFormat("en-GB",{dateStyle:"medium",timeStyle:"short"}).format(new Date(String(v))):"—";

export default function AdminSystemCommandCenter({view}:{view:AdminSystemView}) {
  const current=views.find(v=>v.id===view)||views[0];
  return <div className="docs-shell">
    <div className="page-header"><div><div className="eyebrow accent-eyebrow">ADMINISTRATION & SYSTEM / الإدارة والنظام</div><h1>{current.title}</h1><p>Permission-scoped administration, auditable configuration, secure provider readiness and production system controls.</p></div></div>
    <nav className="docs-subnav">{views.map(v=><a key={v.id} className={v.id===view?"active":""} href={`/admin/${v.id}`}>{v.label}</a>)}</nav>
    {view==="users"?<UsersPanel/>:view==="activity"?<ActivityPanel/>:view==="plants"?<PlantsPanel/>:view==="integrations"?<IntegrationsPanel/>:view==="system-readiness"?<ReadinessPanel/>:<SettingsPanel/>}
  </div>;
}

function State({loading,error,empty,children,onRetry}:{loading:boolean;error:string|null;empty?:boolean;children:React.ReactNode;onRetry:()=>void}) {
  if(loading) return <div className="state-card"><LoaderCircle className="spin" size={24}/><strong>Loading…</strong><span>Reading protected administration data.</span></div>;
  if(error) return <div className="state-card state-error"><strong>Could not load this view</strong><span>{error}</span><button className="secondary-button" onClick={onRetry}>Retry</button></div>;
  if(empty) return <div className="state-card"><Database size={24}/><strong>No records yet</strong><span>This register is connected to production data and currently contains no records.</span></div>;
  return <>{children}</>;
}

function UsersPanel(){
  const [data,setData]=useState<any>({profiles:[],roles:[],permissions:[]}); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null); const [q,setQ]=useState(""); const [open,setOpen]=useState(false);
  const load=useCallback(async()=>{setLoading(true);setError(null);try{setData(await api("/api/admin-system?resource=users"))}catch(e){setError(e instanceof Error?e.message:"Could not load users")}finally{setLoading(false)}},[]);
  useEffect(()=>{void load()},[load]);
  const rows=useMemo(()=>Array.isArray(data?.profiles)?data.profiles.filter((r:any)=>JSON.stringify(r).toLowerCase().includes(q.toLowerCase())):[],[data,q]);
  return <><div className="overview-kpi-grid"><Kpi icon={<Users size={17}/>} label="Users" value={data?.profiles?.length||0} note="Auth-linked profiles"/><Kpi icon={<ShieldCheck size={17}/>} label="Roles" value={data?.roles?.length||0} note="Governed role catalog"/><Kpi icon={<CheckCircle2 size={17}/>} label="Permissions" value={data?.permissions?.length||0} note="Granular permission codes"/></div><section className="panel"><div className="register-toolbar"><div className="search-field"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search users…"/></div><button className="secondary-button" onClick={()=>void load()}><RefreshCw size={14}/> Refresh</button><button className="primary-button" onClick={()=>setOpen(true)}><Plus size={15}/> New user</button></div><State loading={loading} error={error} empty={!rows.length} onRetry={()=>void load()}><div className="table-scroll"><table><thead><tr><th>User</th><th>Role</th><th>Status</th><th>Last sign in</th><th/></tr></thead><tbody>{rows.map((r:any)=><tr key={r.id}><td><strong>{txt(r.display_name,r.email)}</strong><small>{txt(r.email)}</small></td><td>{txt(r.role_code)}</td><td><span className="status-pill"><span className="status-dot"/>{r.is_active?"Active":"Inactive"}</span></td><td>{fmt(r.last_sign_in_at)}</td><td><button className="row-action" onClick={async()=>{await api("/api/admin-system?resource=users",{method:"PATCH",body:JSON.stringify({id:r.id,is_active:!r.is_active})});void load()}}>{r.is_active?"Deactivate":"Activate"}</button></td></tr>)}</tbody></table></div></State></section>{open&&<CreateUser roles={data.roles||[]} close={()=>setOpen(false)} saved={()=>{setOpen(false);void load()}}/>}</>;
}
function CreateUser({roles,close,saved}:{roles:any[];close:()=>void;saved:()=>void}){
  const [v,setV]=useState({email:"",display_name:"",role_code:"viewer",password:""}); const [saving,setSaving]=useState(false); const [error,setError]=useState<string|null>(null);
  async function submit(e:FormEvent){e.preventDefault();setSaving(true);setError(null);try{await api("/api/admin-system?resource=users",{method:"POST",body:JSON.stringify(v)});saved()}catch(e){setError(e instanceof Error?e.message:"Could not create user")}finally{setSaving(false)}}
  return <div className="modal-backdrop"><div className="modal-card"><button className="modal-close" onClick={close}><X size={18}/></button><div className="eyebrow accent-eyebrow">PRIVILEGED USER ADMINISTRATION</div><h2>Create user</h2>{error&&<div className="form-error">{error}</div>}<form className="modal-form" onSubmit={submit}><label>Display name<input required value={v.display_name} onChange={e=>setV({...v,display_name:e.target.value})}/></label><label>Email<input required type="email" value={v.email} onChange={e=>setV({...v,email:e.target.value})}/></label><label>Role<select value={v.role_code} onChange={e=>setV({...v,role_code:e.target.value})}>{roles.map(r=><option key={r.id} value={r.code}>{r.name}</option>)}</select></label><label>Temporary password<input required minLength={12} type="password" value={v.password} onChange={e=>setV({...v,password:e.target.value})}/></label><div className="modal-actions"><button type="button" className="secondary-button" onClick={close}>Cancel</button><button className="primary-button" disabled={saving}>{saving?"Creating…":"Create user"}</button></div></form></div></div>;
}
function ActivityPanel(){const [rows,setRows]=useState<any[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null);const load=useCallback(async()=>{setLoading(true);setError(null);try{setRows(await api("/api/admin-system?resource=activity"))}catch(e){setError(e instanceof Error?e.message:"Could not load activity")}finally{setLoading(false)}},[]);useEffect(()=>{void load()},[load]);const users=new Set(rows.map(r=>r.actor_id).filter(Boolean)).size,modules=new Set(rows.map(r=>r.entity_type)).size,today=new Date().toISOString().slice(0,10);return <><div className="overview-kpi-grid"><Kpi icon={<Activity size={17}/>} label="Activities" value={rows.length} note="Recent audit events"/><Kpi icon={<Users size={17}/>} label="Users" value={users} note="Actors in result"/><Kpi icon={<Database size={17}/>} label="Modules" value={modules} note="Entities touched"/><Kpi icon={<CheckCircle2 size={17}/>} label="Today" value={rows.filter(r=>String(r.created_at).startsWith(today)).length} note="Events today"/></div><section className="panel"><div className="register-toolbar"><button className="secondary-button" onClick={()=>void load()}><RefreshCw size={14}/> Refresh</button></div><State loading={loading} error={error} empty={!rows.length} onRetry={()=>void load()}><div className="table-scroll"><table><thead><tr><th>Date & time</th><th>User</th><th>Action</th><th>Module</th><th>Details</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{fmt(r.created_at)}</td><td>{txt(r.actor?.display_name||r.actor?.email||r.actor_id)}</td><td>{txt(r.event_type)}</td><td>{txt(r.entity_type)}</td><td><small>{JSON.stringify(r.new_data||r.previous_data||{}).slice(0,180)}</small></td></tr>)}</tbody></table></div></State></section></>}

function PlantsPanel(){const [rows,setRows]=useState<any[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[open,setOpen]=useState(false);const load=useCallback(async()=>{setLoading(true);setError(null);try{setRows(await api("/api/admin-system?resource=plants"))}catch(e){setError(e instanceof Error?e.message:"Could not load sites")}finally{setLoading(false)}},[]);useEffect(()=>{void load()},[load]);return <section className="panel"><div className="register-toolbar"><button className="secondary-button" onClick={()=>void load()}><RefreshCw size={14}/> Refresh</button><button className="primary-button" onClick={()=>setOpen(true)}><Plus size={15}/> Add site</button><button className="secondary-button" onClick={()=>window.print()}>Print Directory</button></div><State loading={loading} error={error} empty={!rows.length} onRetry={()=>void load()}><div className="table-scroll"><table><thead><tr><th>Code</th><th>Facility</th><th>Manager</th><th>Location</th><th>Industry</th><th>Status</th><th>Timezone</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{txt(r.code)}</td><td><strong>{txt(r.name)}</strong><small>{txt(r.name_ar,"")}</small></td><td>{txt(r.manager_name)}</td><td>{txt(r.location)}</td><td>{txt(r.industry)}</td><td>{txt(r.status)}</td><td>{txt(r.timezone)}</td></tr>)}</tbody></table></div></State>{open&&<CreatePlant close={()=>setOpen(false)} saved={()=>{setOpen(false);void load()}}/>}</section>}
function CreatePlant({close,saved}:{close:()=>void;saved:()=>void}){const [v,setV]=useState({name:"",name_ar:"",code:"",manager_name:"",location:"",industry:"",status:"active",timezone:"Asia/Riyadh"});const [saving,setSaving]=useState(false),[error,setError]=useState<string|null>(null);async function submit(e:FormEvent){e.preventDefault();setSaving(true);try{await api("/api/admin-system?resource=plants",{method:"POST",body:JSON.stringify(v)});saved()}catch(e){setError(e instanceof Error?e.message:"Could not save site")}finally{setSaving(false)}}return <div className="modal-backdrop"><div className="modal-card"><button className="modal-close" onClick={close}><X size={18}/></button><h2>Add facility / work site</h2>{error&&<div className="form-error">{error}</div>}<form className="modal-form" onSubmit={submit}><label>English name<input required value={v.name} onChange={e=>setV({...v,name:e.target.value})}/></label><label>Arabic name<input value={v.name_ar} onChange={e=>setV({...v,name_ar:e.target.value})}/></label><label>Plant code<input required value={v.code} onChange={e=>setV({...v,code:e.target.value})}/></label><label>Manager<input value={v.manager_name} onChange={e=>setV({...v,manager_name:e.target.value})}/></label><label>Location<input value={v.location} onChange={e=>setV({...v,location:e.target.value})}/></label><label>Industry<input value={v.industry} onChange={e=>setV({...v,industry:e.target.value})}/></label><label>Status<select value={v.status} onChange={e=>setV({...v,status:e.target.value})}><option value="active">Active</option><option value="maintenance">Maintenance</option><option value="inactive">Inactive</option></select></label><div className="modal-actions"><button type="button" className="secondary-button" onClick={close}>Cancel</button><button className="primary-button" disabled={saving}>{saving?"Saving…":"Save site"}</button></div></form></div></div>}

function IntegrationsPanel(){const [data,setData]=useState<any>(),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null);const load=useCallback(async()=>{setLoading(true);setError(null);try{setData(await api("/api/admin-system?resource=integrations"))}catch(e){setError(e instanceof Error?e.message:"Could not load integrations")}finally{setLoading(false)}},[]);useEffect(()=>{void load()},[load]);return <State loading={loading} error={error} empty={false} onRetry={()=>void load()}><div className="overview-kpi-grid">{["email","whatsapp","teams","in_app"].map(k=><Kpi key={k} icon={<Settings2 size={17}/>} label={k.replace("_"," ").toUpperCase()} value={data?.providers?.[k]?.ready?"Ready":"Setup"} note={data?.providers?.[k]?.source||"Server-side configuration"}/>)}</div><section className="panel"><h2>Notification outbox</h2><p>Provider secrets stay on the server. This view exposes readiness and delivery state only.</p><div className="overview-kpi-grid"><Kpi icon={<Database size={17}/>} label="Pending" value={data?.outbox?.pending||0} note="Awaiting delivery"/><Kpi icon={<CheckCircle2 size={17}/>} label="Sent" value={data?.outbox?.sent||0} note="Delivered"/><Kpi icon={<Activity size={17}/>} label="Failed" value={data?.outbox?.failed||0} note="Needs review"/></div><button className="secondary-button" onClick={async()=>{await api("/api/admin-system?resource=integrations&action=retry-failed",{method:"POST",body:"{}"});void load()}}>Retry failed queue</button></section></State>}

function ReadinessPanel(){const [data,setData]=useState<any>(),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null);const load=useCallback(async()=>{setLoading(true);setError(null);try{setData(await api("/api/admin-system?resource=system-readiness"))}catch(e){setError(e instanceof Error?e.message:"Could not load readiness")}finally{setLoading(false)}},[]);useEffect(()=>{void load()},[load]);const checks=Object.entries(data?.checks||{});return <State loading={loading} error={error} empty={false} onRetry={()=>void load()}><section className="panel"><div className="register-toolbar"><button className="secondary-button" onClick={()=>void load()}><RefreshCw size={14}/> Refresh</button></div><div className="overview-kpi-grid">{checks.map(([k,v]:any)=><Kpi key={k} icon={<ShieldCheck size={17}/>} label={k.replaceAll("_"," ")} value={v?.ok?"Ready":"Needs attention"} note={v?.detail||""}/>)}</div></section></State>}

function SettingsPanel(){const [rows,setRows]=useState<any[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[saving,setSaving]=useState(false);const branding=rows.find(r=>r.key==="branding")?.value||{};const [form,setForm]=useState<any>({board_name:"KSA SAFETY BOARD",company_name:"",logo_url:""});const load=useCallback(async()=>{setLoading(true);setError(null);try{const d=await api("/api/admin-system?resource=settings");setRows(d);const b=d.find((r:any)=>r.key==="branding")?.value||{};setForm({board_name:b.board_name||"KSA SAFETY BOARD",company_name:b.company_name||"",logo_url:b.logo_url||""})}catch(e){setError(e instanceof Error?e.message:"Could not load settings")}finally{setLoading(false)}},[]);useEffect(()=>{void load()},[load]);async function save(e:FormEvent){e.preventDefault();setSaving(true);try{await api("/api/admin-system?resource=settings",{method:"PATCH",body:JSON.stringify({key:"branding",value:{...branding,...form}})});await load()}catch(e){setError(e instanceof Error?e.message:"Could not save settings")}finally{setSaving(false)}}return <State loading={loading} error={error} empty={false} onRetry={()=>void load()}><section className="panel settings-panel"><h2>Branding & document identity</h2><p>Logo configuration accepts an internal path or HTTPS URL. Base64 data is rejected server-side.</p><form className="modal-form" onSubmit={save}><label>Board name<input required value={form.board_name} onChange={e=>setForm({...form,board_name:e.target.value})}/></label><label>Company name<input value={form.company_name} onChange={e=>setForm({...form,company_name:e.target.value})}/></label><label>Logo URL / internal path<input value={form.logo_url} onChange={e=>setForm({...form,logo_url:e.target.value})} placeholder="/branding/logo.png or https://…"/></label><button className="primary-button" disabled={saving}>{saving?"Saving…":"Save settings"}</button></form><div className="register-note"><ShieldCheck size={17}/><div><strong>Print identity is centralized.</strong><span>Templates must consume the branding setting rather than hardcoding legacy board names.</span></div></div></section></State>}

function Kpi({icon,label,value,note}:{icon:React.ReactNode;label:string;value:string|number;note:string}){return <div className="overview-kpi"><div className="overview-kpi-icon">{icon}</div><div><span>{label}</span><strong>{value}</strong><small>{note}</small></div></div>}
