"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { Activity, AlertTriangle, Camera, CheckCircle2, CircleDot, Cpu, Eye, FileVideo, Flame, Grid2X2, LayoutDashboard, LoaderCircle, Map, Plus, Radio, RefreshCw, Search, Settings2, ShieldAlert, SlidersHorizontal, TriangleAlert, Users, X } from "lucide-react";
import { useRouter } from "next/navigation";
import type { User } from "@supabase/supabase-js";
import { supabase } from "@/lib/supabase";

export type VisionView = "dashboard" | "live" | "cameras" | "devices" | "map" | "rules" | "events" | "alerts" | "analytics" | "settings";
type CameraRow = { id: string; camera_code: string; name: string; area: string | null; zone: string | null; camera_type: string; rtsp_configured: boolean; stream_gateway_type: string; stream_gateway_ref: string | null; resolution: string | null; fps: number | null; nvr_server: string | null; nvr_channel: string | null; recording_enabled: boolean; analytics_enabled: boolean; enabled: boolean; camera_state: string; stream_state: string; analytics_state: string; last_seen_at: string | null; last_frame_at: string | null; position: Record<string, unknown>; device_id: string | null };
type DeviceRow = { id: string; device_code: string; name: string; device_type: string; status: string; firmware_version: string | null; hardware_model: string | null; last_seen_at: string | null; heartbeat_at: string | null; cpu_percent: number | null; memory_percent: number | null; temperature_c: number | null; storage_percent: number | null; network_strength: number | null; provisioning_state: string };
type AlertRow = { id: string; event_key: string; category: string; violation_type: string; severity: string; status: string; confidence: number | null; camera_id: string | null; device_id: string | null; zone_id: string | null; event_timestamp: string; received_at: string; human_verified: boolean | null; acknowledgement_note: string | null };
type RuleRow = { id: string; name: string; category: string; severity: string; status: string; camera_id: string | null };

const views: Array<{ id: VisionView; label: string; icon: typeof Camera }> = [
  { id: "dashboard", label: "Dashboard", icon: LayoutDashboard }, { id: "live", label: "Camera wall", icon: Grid2X2 }, { id: "cameras", label: "Cameras", icon: Camera }, { id: "devices", label: "ESP devices", icon: Cpu }, { id: "map", label: "Facility map", icon: Map }, { id: "rules", label: "Safety rules", icon: SlidersHorizontal }, { id: "events", label: "Safety events", icon: Activity }, { id: "alerts", label: "Alerts", icon: TriangleAlert }, { id: "analytics", label: "Analytics", icon: Activity }, { id: "settings", label: "Settings", icon: Settings2 },
];

async function api<T>(path: string, init: RequestInit = {}) { if (!supabase) throw new Error("Supabase is not configured."); const session = await supabase.auth.getSession(); const token = session.data.session?.access_token; const response = await fetch(path, { ...init, headers: { "Content-Type": "application/json", ...(token ? { Authorization: `Bearer ${token}` } : {}), ...(init.headers ?? {}) } }); const payload = await response.json().catch(() => ({ ok: false, error: "Invalid API response." })); if (!response.ok || !payload.ok) throw new Error(payload.error ?? "Vision request failed."); return payload.data as T; }
function statusTone(value: string) { const v = value.toLowerCase(); return v.includes("online") || v.includes("active") || v.includes("healthy") || v.includes("resolved") ? "status-green" : v.includes("critical") || v.includes("offline") || v.includes("error") || v.includes("high") ? "status-red" : v.includes("warning") || v.includes("degraded") || v.includes("new") ? "status-amber" : "status-neutral"; }
function Status({ value }: { value: string }) { return <span className={`status-pill ${statusTone(value)}`}><span className="status-dot" />{value.replaceAll("_", " ")}</span>; }
function date(value: string | null) { return value ? new Intl.DateTimeFormat("en-GB", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "—"; }

type Props = { user: User; view: VisionView };
export default function VisionCommandCenter({ user, view }: Props) {
  const router = useRouter(); const [cameras, setCameras] = useState<CameraRow[]>([]); const [devices, setDevices] = useState<DeviceRow[]>([]); const [alerts, setAlerts] = useState<AlertRow[]>([]); const [rules, setRules] = useState<RuleRow[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [search, setSearch] = useState(""); const [wallSize, setWallSize] = useState<1 | 2 | 3 | 4>(2); const [showCameraForm, setShowCameraForm] = useState(false); const [cameraName, setCameraName] = useState(""); const [cameraCode, setCameraCode] = useState(""); const [cameraArea, setCameraArea] = useState(""); const [cameraGateway, setCameraGateway] = useState("none"); const [showRuleForm, setShowRuleForm] = useState(false); const [ruleName, setRuleName] = useState(""); const [ruleCategory, setRuleCategory] = useState("ppe"); const [ruleSeverity, setRuleSeverity] = useState("medium"); const [saving, setSaving] = useState(false);

  const load = useCallback(async () => { setLoading(true); setError(null); try { const [cameraData, deviceData, alertData, ruleData] = await Promise.all([api<CameraRow[]>("/api/vision-cameras"), api<DeviceRow[]>("/api/vision-devices"), api<AlertRow[]>("/api/vision-alerts"), api<RuleRow[]>("/api/vision-rules")]); setCameras(cameraData); setDevices(deviceData); setAlerts(alertData); setRules(ruleData); } catch (loadError) { setError(loadError instanceof Error ? loadError.message : "Vision data could not be loaded."); } finally { setLoading(false); } }, []);
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, [load]);
  useEffect(() => { const client = supabase; if (!client) return; const channel = client.channel("vision-command-center").on("postgres_changes", { event: "*", schema: "public", table: "vision_cameras" }, () => { void load(); }).on("postgres_changes", { event: "*", schema: "public", table: "vision_devices" }, () => { void load(); }).on("postgres_changes", { event: "*", schema: "public", table: "vision_alerts" }, () => { void load(); }).subscribe(); return () => { void client.removeChannel(channel); }; }, [load]);
  function go(next: VisionView) { router.push(`/admin/vision/${next}`); }
  const online = cameras.filter((item) => item.camera_state === "online").length; const offline = cameras.filter((item) => ["offline", "disabled"].includes(item.camera_state)).length; const activeAlerts = alerts.filter((item) => !["resolved", "false_positive"].includes(item.status)).length; const ppeAlerts = alerts.filter((item) => item.category === "ppe" && !["resolved", "false_positive"].includes(item.status)).length;
  const filteredCameras = cameras.filter((item) => `${item.name} ${item.camera_code} ${item.area ?? ""} ${item.zone ?? ""}`.toLowerCase().includes(search.toLowerCase()));

  async function createCamera(event: FormEvent) { event.preventDefault(); setSaving(true); setError(null); try { await api("/api/vision-cameras", { method: "POST", body: JSON.stringify({ name: cameraName, camera_code: cameraCode, area: cameraArea, stream_gateway_type: cameraGateway }) }); setShowCameraForm(false); setCameraName(""); setCameraCode(""); setCameraArea(""); await load(); } catch (saveError) { setError(saveError instanceof Error ? saveError.message : "Camera could not be saved."); } finally { setSaving(false); } }
  async function createRule(event: FormEvent) { event.preventDefault(); setSaving(true); setError(null); try { await api("/api/vision-rules", { method: "POST", body: JSON.stringify({ name: ruleName, category: ruleCategory, severity: ruleSeverity }) }); setShowRuleForm(false); setRuleName(""); await load(); } catch (saveError) { setError(saveError instanceof Error ? saveError.message : "Rule could not be saved."); } finally { setSaving(false); } }
  async function alertAction(alert: AlertRow, status: string) { setSaving(true); try { await api("/api/vision-alerts", { method: "PATCH", body: JSON.stringify({ id: alert.id, status }) }); await load(); } catch (actionError) { setError(actionError instanceof Error ? actionError.message : "Alert action failed."); } finally { setSaving(false); } }

  const header = <div className="vision-header"><div><div className="eyebrow accent-eyebrow">ESP SAFETY VISION</div><h1>{views.find((item) => item.id === view)?.label ?? "Vision"}</h1><p>Industrial camera, edge-device, alert, and analytics operations with truthful stream health.</p></div><div className="vision-header-actions"><span className="vision-live-state"><Radio size={14} /> Realtime health channel</span>{(view === "cameras" || view === "live") && <button className="primary-button" onClick={() => setShowCameraForm(true)}><Plus size={15} /> Add camera</button>}{view === "rules" && <button className="primary-button" onClick={() => setShowRuleForm(true)}><Plus size={15} /> Create rule</button>}</div></div>;
  const nav = <div className="vision-subnav">{views.map(({ id, label, icon: Icon }) => <button key={id} className={view === id ? "active" : ""} onClick={() => go(id)}><Icon size={14} />{label}</button>)}</div>;
  if (loading) return <div className="vision-shell">{header}{nav}<div className="state-card"><LoaderCircle className="spin" size={24} /><strong>Loading Vision operations…</strong><span>Reading camera, device, and alert health from protected records.</span></div></div>;
  if (error && !cameras.length && !devices.length && !alerts.length) return <div className="vision-shell">{header}{nav}<div className="state-card state-error"><AlertTriangle size={24} /><strong>Vision service unavailable</strong><span>{error}</span><button className="secondary-button" onClick={() => void load()}><RefreshCw size={15} /> Retry</button></div></div>;

  return <div className="vision-shell" data-operator={user.id}>{header}{nav}{error && <div className="form-error" role="alert">{error}</div>}
    {view === "dashboard" && <><section className="vision-kpi-grid"><div className="vision-kpi"><Camera size={18} /><span>Total cameras</span><strong>{cameras.length}</strong><small>Protected directory</small></div><div className="vision-kpi green"><CheckCircle2 size={18} /><span>Online cameras</span><strong>{online}</strong><small>Network + camera state</small></div><div className="vision-kpi red"><TriangleAlert size={18} /><span>Offline cameras</span><strong>{offline}</strong><small>Requires attention</small></div><div className="vision-kpi amber"><ShieldAlert size={18} /><span>Active alerts</span><strong>{activeAlerts}</strong><small>{ppeAlerts} PPE alerts</small></div></section><div className="vision-dashboard-grid"><section className="panel"><div className="panel-heading"><div><div className="eyebrow">HEALTH POSTURE</div><h2>Infrastructure state</h2></div><Activity className="panel-mark" size={19} /></div><div className="vision-health-list"><div><Cpu size={16} /><span>Edge devices</span><strong>{devices.filter((item) => item.status === "active").length} active / {devices.length}</strong></div><div><Camera size={16} /><span>Stream gateways</span><strong>{cameras.filter((item) => item.stream_gateway_type !== "none").length} configured</strong></div><div><Eye size={16} /><span>AI analytics</span><strong>{cameras.filter((item) => item.analytics_enabled).length} enabled</strong></div><div><Flame size={16} /><span>Fire / smoke rules</span><strong>{rules.filter((item) => item.category === "fire_smoke" && item.status === "active").length} active</strong></div></div></section><section className="panel"><div className="panel-heading"><div><div className="eyebrow">RECENT SAFETY SIGNALS</div><h2>Alerts requiring review</h2></div><button className="text-button" onClick={() => go("alerts")}>Open center</button></div>{alerts.length === 0 ? <div className="state-card compact"><CheckCircle2 size={20} /><strong>No alerts recorded</strong><span>Only persisted detection events appear here.</span></div> : <div className="vision-alert-list">{alerts.slice(0, 5).map((alert) => <div className="vision-alert-row" key={alert.id}><Status value={alert.severity} /><div><strong>{alert.violation_type}</strong><small>{date(alert.event_timestamp)} · {alert.category}</small></div><Status value={alert.status} /></div>)}</div>}</section></div></>}
    {view === "live" && <section className="panel"><div className="panel-heading"><div><div className="eyebrow">LIVE MONITORING</div><h2>Camera wall</h2></div><div className="wall-controls"><Search size={14} /><input aria-label="Search cameras" placeholder="Search camera, area, ID…" value={search} onChange={(event) => setSearch(event.target.value)} />{([1, 2, 3, 4] as const).map((size) => <button key={size} className={wallSize === size ? "selected" : ""} onClick={() => setWallSize(size)}>{size}×{size}</button>)}</div></div>{filteredCameras.length === 0 ? <div className="state-card"><Camera size={22} /><strong>No cameras match this filter</strong><span>Add a camera or adjust the search. No fake live tiles are shown.</span></div> : <div className={`camera-wall wall-${wallSize}`}>{filteredCameras.map((camera) => <div className="camera-tile" key={camera.id}><div className="camera-tile-top"><strong>{camera.name}</strong><Status value={camera.camera_state} /></div><div className="camera-frame">{camera.stream_gateway_type === "none" ? <div><FileVideo size={25} /><strong>Preview unavailable</strong><span>No WebRTC/HLS gateway configured</span></div> : camera.stream_state !== "healthy" ? <div><TriangleAlert size={25} /><strong>Stream {camera.stream_state}</strong><span>Gateway configured but not healthy</span></div> : <div><Radio size={25} /><strong>Configured gateway</strong><span>Authenticated preview adapter ready</span></div>}</div><div className="camera-tile-meta"><span>{camera.area || "Unassigned area"}</span><span>{camera.recording_enabled ? "● Recording" : "Recording off"}</span><span>{camera.resolution || "Resolution —"}</span></div></div>)}</div>}</section>}
    {view === "cameras" && <section className="panel"><div className="panel-heading"><div><div className="eyebrow">CAMERA DIRECTORY</div><h2>Registered cameras</h2></div><button className="secondary-button" onClick={() => void load()}><RefreshCw size={14} /> Refresh</button></div><div className="vision-table-wrap"><table className="vision-table"><thead><tr><th>Camera</th><th>Location</th><th>Camera state</th><th>Stream</th><th>AI</th><th>Gateway / NVR</th></tr></thead><tbody>{cameras.length === 0 ? <tr><td colSpan={6}><div className="table-empty">No camera records.</div></td></tr> : cameras.map((camera) => <tr key={camera.id}><td><strong>{camera.name}</strong><small>{camera.camera_code} · {camera.camera_type}</small></td><td>{camera.area || "—"}{camera.zone ? ` · ${camera.zone}` : ""}</td><td><Status value={camera.camera_state} /></td><td><Status value={camera.stream_state} /></td><td>{camera.analytics_enabled ? <Status value={camera.analytics_state} /> : <span className="muted-copy">Disabled</span>}</td><td>{camera.stream_gateway_type !== "none" ? `${camera.stream_gateway_type} · ${camera.nvr_server || "No NVR"}` : "Not configured"}</td></tr>)}</tbody></table></div></section>}
    {view === "devices" && <section className="panel"><div className="panel-heading"><div><div className="eyebrow">ESP EDGE DEVICES</div><h2>Device health</h2></div><Cpu className="panel-mark" size={20} /></div><div className="vision-table-wrap"><table className="vision-table"><thead><tr><th>Device</th><th>Lifecycle</th><th>Last heartbeat</th><th>CPU / memory</th><th>Temperature</th><th>Provisioning</th></tr></thead><tbody>{devices.length === 0 ? <tr><td colSpan={6}><div className="table-empty">No edge devices registered. Discovery must come from the authenticated ESP ingestion path.</div></td></tr> : devices.map((device) => <tr key={device.id}><td><strong>{device.name}</strong><small>{device.device_code} · {device.hardware_model || device.device_type}</small></td><td><Status value={device.status} /></td><td>{date(device.heartbeat_at || device.last_seen_at)}</td><td>{device.cpu_percent ?? "—"}% / {device.memory_percent ?? "—"}%</td><td>{device.temperature_c ?? "—"}°C</td><td><Status value={device.provisioning_state} /></td></tr>)}</tbody></table></div></section>}
    {view === "map" && <section className="panel"><div className="panel-heading"><div><div className="eyebrow">FACILITY MAP</div><h2>Camera and device positions</h2></div><Map className="panel-mark" size={20} /></div><div className="vision-map">{cameras.length === 0 ? <div className="state-card"><Map size={22} /><strong>No mapped cameras</strong><span>Save camera positions before showing facility markers.</span></div> : cameras.map((camera, index) => <button className="map-marker" style={{ left: `${18 + (index * 17) % 72}%`, top: `${22 + (index * 23) % 55}%` }} key={camera.id} onClick={() => go("cameras")}><span className={statusTone(camera.camera_state)}><CircleDot size={12} /></span><strong>{camera.name}</strong><small>{camera.area || "Unassigned"}</small></button>)}</div></section>}
    {view === "rules" && <section className="panel"><div className="panel-heading"><div><div className="eyebrow">DETECTION GOVERNANCE</div><h2>Safety rules</h2></div><button className="secondary-button" onClick={() => void load()}><RefreshCw size={14} /> Refresh</button></div><div className="vision-rule-grid">{rules.length === 0 ? <div className="state-card"><SlidersHorizontal size={22} /><strong>No rules configured</strong><span>Rules must be created before AI events are considered actionable.</span></div> : rules.map((rule) => <div className="vision-rule-card" key={rule.id}><div className="panel-heading"><strong>{rule.name}</strong><Status value={rule.status} /></div><span>{rule.category} · {rule.severity}</span><small>{rule.camera_id ? "Camera scoped" : "All configured cameras"}</small></div>)}</div></section>}
    {(view === "events" || view === "alerts") && <section className="panel"><div className="panel-heading"><div><div className="eyebrow">{view === "alerts" ? "ALERTS CENTER" : "EVENT REGISTER"}</div><h2>{view === "alerts" ? "Safety alerts" : "Persisted detection events"}</h2></div><button className="secondary-button" onClick={() => void load()}><RefreshCw size={14} /> Refresh</button></div><div className="vision-alert-list large">{alerts.length === 0 ? <div className="state-card"><Activity size={22} /><strong>No persisted Vision events</strong><span>No synthetic events are generated in the UI.</span></div> : alerts.map((alert) => <div className="vision-alert-row detailed" key={alert.id}><Status value={alert.severity} /><div><strong>{alert.violation_type}</strong><small>{alert.category} · {date(alert.event_timestamp)} · confidence {alert.confidence === null ? "—" : `${Math.round(alert.confidence * 100)}%`}</small></div><Status value={alert.status} /><div className="alert-actions">{alert.status === "new" && <button className="secondary-button" disabled={saving} onClick={() => void alertAction(alert, "acknowledged")}>Acknowledge</button>}{!["resolved", "false_positive"].includes(alert.status) && <button className="secondary-button" disabled={saving} onClick={() => void alertAction(alert, "resolved")}>Resolve</button>}{!["resolved", "false_positive"].includes(alert.status) && <button className="text-button" disabled={saving} onClick={() => void alertAction(alert, "false_positive")}>False positive</button>}</div></div>)}</div></section>}
    {view === "analytics" && <><section className="vision-kpi-grid"><div className="vision-kpi"><Activity size={18} /><span>Total events</span><strong>{alerts.length}</strong><small>Persisted records only</small></div><div className="vision-kpi amber"><ShieldAlert size={18} /><span>PPE share</span><strong>{alerts.length ? Math.round((ppeAlerts / alerts.length) * 100) : 0}%</strong><small>Current loaded range</small></div><div className="vision-kpi green"><CheckCircle2 size={18} /><span>Resolved</span><strong>{alerts.filter((item) => item.status === "resolved").length}</strong><small>Human workflow result</small></div><div className="vision-kpi red"><TriangleAlert size={18} /><span>False positive</span><strong>{alerts.filter((item) => item.status === "false_positive").length}</strong><small>Review quality signal</small></div></section><section className="panel"><div className="panel-heading"><div><div className="eyebrow">DISTRIBUTION</div><h2>Events by category</h2></div><Activity className="panel-mark" size={20} /></div><div className="analytics-bars">{["ppe", "restricted_zone", "equipment", "fire_smoke", "people_vehicle", "proximity"].map((category) => { const count = alerts.filter((item) => item.category === category).length; const width = alerts.length ? `${Math.max(3, (count / alerts.length) * 100)}%` : "3%"; return <div key={category}><span>{category.replaceAll("_", " ")}</span><div><i style={{ width }} /></div><strong>{count}</strong></div>; })}</div></section></>}
    {view === "settings" && <section className="panel"><div className="panel-heading"><div><div className="eyebrow">VISION SETTINGS</div><h2>Operational boundaries</h2></div><Settings2 className="panel-mark" size={20} /></div><div className="settings-notice"><ShieldAlert size={18} /><div><strong>Gateway and device credentials stay server-side.</strong><span>RTSP passwords, device tokens, and signed playback URLs are never returned to the browser directory.</span></div></div><div className="vision-health-list"><div><FileVideo size={16} /><span>Browser playback</span><strong>{cameras.some((camera) => camera.stream_gateway_type !== "none") ? "Gateway configured" : "Not configured"}</strong></div><div><Radio size={16} /><span>Raw RTSP exposure</span><strong>Blocked</strong></div><div><Users size={16} /><span>Realtime source</span><strong>State and alerts only</strong></div></div></section>}
    {showCameraForm && <div className="modal-backdrop"><div className="modal-card"><button className="modal-close" onClick={() => setShowCameraForm(false)} aria-label="Close"><X size={18} /></button><div className="eyebrow accent-eyebrow">CAMERA DIRECTORY</div><h2>Add camera</h2><form className="modal-form" onSubmit={createCamera}><label>Camera name<input required value={cameraName} onChange={(event) => setCameraName(event.target.value)} /></label><label>Camera ID<input required value={cameraCode} onChange={(event) => setCameraCode(event.target.value)} /></label><label>Area / zone<input value={cameraArea} onChange={(event) => setCameraArea(event.target.value)} /></label><label>Browser gateway<select value={cameraGateway} onChange={(event) => setCameraGateway(event.target.value)}><option value="none">None — preview unavailable</option><option value="webrtc">WebRTC gateway</option><option value="hls">HLS gateway</option><option value="ll_hls">Low-latency HLS gateway</option></select></label><div className="modal-actions"><button type="button" className="secondary-button" onClick={() => setShowCameraForm(false)}>Cancel</button><button className="primary-button" disabled={saving}>{saving ? <LoaderCircle className="spin" size={15} /> : <Plus size={15} />} Save camera</button></div></form></div></div>}
    {showRuleForm && <div className="modal-backdrop"><div className="modal-card"><button className="modal-close" onClick={() => setShowRuleForm(false)} aria-label="Close"><X size={18} /></button><div className="eyebrow accent-eyebrow">DETECTION GOVERNANCE</div><h2>Create safety rule</h2><form className="modal-form" onSubmit={createRule}><label>Rule name<input required value={ruleName} onChange={(event) => setRuleName(event.target.value)} /></label><label>Category<select value={ruleCategory} onChange={(event) => setRuleCategory(event.target.value)}><option value="ppe">PPE</option><option value="restricted_zone">Restricted zone</option><option value="equipment">Equipment</option><option value="behavioral">Behavioral</option><option value="fire_smoke">Fire / smoke</option><option value="people_vehicle">People / vehicle</option><option value="proximity">Proximity</option></select></label><label>Severity<select value={ruleSeverity} onChange={(event) => setRuleSeverity(event.target.value)}><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option><option value="critical">Critical</option></select></label><div className="modal-actions"><button type="button" className="secondary-button" onClick={() => setShowRuleForm(false)}>Cancel</button><button className="primary-button" disabled={saving}>{saving ? <LoaderCircle className="spin" size={15} /> : <Plus size={15} />} Save rule</button></div></form></div></div>}
  </div>;
}
