/* eslint-disable @typescript-eslint/no-explicit-any */
import { NextRequest } from "next/server";
import { cleanText } from "@/lib/live-meeting";
import { isAuthContext, requireAuth } from "@/lib/server-auth";
const fields = "id,license_number,category,facility_name,facility_code,site_id,site_name,site_address,issuing_authority,issue_date,expiry_date,state,renewal_required,renewal_owner_id,renewal_notes,remarks,evidence_url,created_by,created_at,updated_at";
const categories = ["environmental","civil_defense","municipal","industrial","other_regulatory"];
const states = ["ACTIVE","EXPIRING_SOON","EXPIRED","PENDING_RENEWAL"];
function error(message: string, status = 422) { return Response.json({ ok: false, error: message }, { status }); }
function derivedState(expiry: unknown, stored: unknown) { if (!expiry) return stored || "ACTIVE"; const days = Math.ceil((new Date(String(expiry)).getTime() - Date.now()) / 86400000); if (days < 0) return "EXPIRED"; if (days <= 60) return "EXPIRING_SOON"; return stored === "PENDING_RENEWAL" ? stored : "ACTIVE"; }
const val = (body: Record<string, unknown> | null, key: string, max = 500) => cleanText(body?.[key], max) || null;
function decorate(row: Record<string, unknown>) { return { ...row, effective_state: derivedState(row.expiry_date, row.state), expiry_warning: row.expiry_date ? Math.ceil((new Date(String(row.expiry_date)).getTime() - Date.now()) / 86400000) : null }; }
export async function GET(request: NextRequest) { const auth = await requireAuth(request); if (!isAuthContext(auth)) return auth; const p = request.nextUrl.searchParams; const { data, error: dbError } = await (auth.client as any).from("facility_regulatory_licenses").select(fields).order("expiry_date", { ascending: true }).limit(250); if (dbError) return error(dbError.message, 500); let rows = (data ?? []).map(decorate); if (p.get("category")) rows = rows.filter((r: any) => r.category === p.get("category")); if (p.get("state")) rows = rows.filter((r: any) => r.effective_state === p.get("state")); return Response.json({ ok: true, data: rows }); }
export async function POST(request: NextRequest) { const auth = await requireAuth(request); if (!isAuthContext(auth)) return auth; if (!auth.isStaff) return error("Facility license changes require HSE staff access.", 403); const body = await request.json().catch(() => null) as Record<string, unknown> | null; const number = val(body, "license_number", 100); const facility = val(body, "facility_name", 200); const authority = val(body, "issuing_authority", 200); const category = val(body, "category", 40); if (!number || !facility || !authority || !category || !categories.includes(category)) return error("License number, category, facility, and issuing authority are required."); const state = val(body, "state", 30) || "ACTIVE"; if (!states.includes(state)) return error("Invalid license state."); const payload = { license_number: number, category, facility_name: facility, facility_code: val(body, "facility_code", 80), site_id: val(body, "site_id", 80), site_name: val(body, "site_name", 160), site_address: val(body, "site_address", 300), issuing_authority: authority, issue_date: val(body, "issue_date", 20), expiry_date: val(body, "expiry_date", 20), state, renewal_required: body?.renewal_required !== false, renewal_owner_id: val(body, "renewal_owner_id", 80), renewal_notes: val(body, "renewal_notes", 2000), remarks: val(body, "remarks", 2000), evidence_url: val(body, "evidence_url", 500), created_by: auth.user.id }; const { data, error: dbError } = await (auth.client as any).from("facility_regulatory_licenses").insert(payload).select(fields).single(); if (dbError || !data) return error(dbError?.message ?? "Facility license could not be created."); return Response.json({ ok: true, data: decorate(data) }, { status: 201 }); }
export async function PATCH(request: NextRequest) { const auth = await requireAuth(request); if (!isAuthContext(auth)) return auth; if (!auth.isStaff) return error("Facility license changes require HSE staff access.", 403); const body = await request.json().catch(() => null) as Record<string, unknown> | null; const id = val(body, "id", 80); if (!id) return error("License ID is required."); const patch: Record<string, unknown> = {}; for (const key of ["license_number","category","facility_name","facility_code","site_name","site_address","issuing_authority","issue_date","expiry_date","state","renewal_notes","remarks","evidence_url"]) if (body?.[key] !== undefined) patch[key] = val(body, key, 2000); if (body?.renewal_required !== undefined) patch.renewal_required = Boolean(body.renewal_required); if (body?.renewal_owner_id !== undefined) patch.renewal_owner_id = val(body, "renewal_owner_id", 80); patch.updated_at = new Date().toISOString(); const { data, error: dbError } = await (auth.client as any).from("facility_regulatory_licenses").update(patch).eq("id", id).select(fields).single(); if (dbError || !data) return error(dbError?.message ?? "Facility license could not be updated."); return Response.json({ ok: true, data: decorate(data) }); }
export async function DELETE(request: NextRequest) { const auth = await requireAuth(request); if (!isAuthContext(auth)) return auth; if (!auth.isStaff) return error("Facility license changes require HSE staff access.", 403); const id = request.nextUrl.searchParams.get("id"); if (!id) return error("License ID is required."); const { error: dbError } = await (auth.client as any).from("facility_regulatory_licenses").delete().eq("id", id); if (dbError) return error(dbError.message, 500); return Response.json({ ok: true, data: { id, deleted: true } }); }
