-- KSA SAFETY BOARD / Section 08 Safety Systems & Emergency Preparedness
insert into public.permissions(code,description) values
 ('life_safety.read','Read life safety operations'),('life_safety.manage','Manage life safety operations'),
 ('fire.manage','Manage fire protection systems'),('emergency.manage','Manage emergency response'),
 ('emergency.drill.manage','Manage emergency drills'),('assets.read','Read safety assets'),('assets.manage','Manage safety assets'),
 ('contractor_safety.read','Read contractor safety'),('contractor_safety.manage','Manage contractor safety'),('visitors.manage','Manage visitors'),('safety_map.manage','Manage safety maps') on conflict (code) do nothing;
create table if not exists public.fire_gateways (id uuid primary key default gen_random_uuid(), gateway_no text not null unique, name text not null, factory text, location text, status text not null default 'normal' check(status in ('normal','fault','offline','maintenance')), last_seen timestamptz, notes text, created_by uuid references public.profiles(id), created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.fire_panels (id uuid primary key default gen_random_uuid(), gateway_id uuid references public.fire_gateways(id) on delete set null, panel_no text not null unique, name text not null, panel_type text, location text, status text not null default 'normal' check(status in ('normal','alarm','pre_alarm','supervisory','fault','offline','maintenance')), last_event_at timestamptz, created_by uuid references public.profiles(id), created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.fire_devices (id uuid primary key default gen_random_uuid(), panel_id uuid references public.fire_panels(id) on delete set null, device_no text not null unique, device_type text not null check(device_type in ('smoke_detector','heat_detector','manual_call_point','sounder','strobe','sprinkler','pump','gas_detector','other')), name text not null, building text, floor text, zone text, status text not null default 'good' check(status in ('good','alarm','fault','offline','inspection_due','maintenance_due','damaged','out_of_service','expired')), last_inspection date, next_inspection date, qr_code text unique, notes text, created_by uuid references public.profiles(id), created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.fire_events (id uuid primary key default gen_random_uuid(), device_id uuid references public.fire_devices(id) on delete set null, panel_id uuid references public.fire_panels(id) on delete set null, event_type text not null check(event_type in ('alarm','pre_alarm','supervisory','fault','offline','restored','inspection')), severity text not null default 'high' check(severity in ('low','medium','high','critical')), status text not null default 'new' check(status in ('new','acknowledged','resolved','false_alarm')), message text not null, occurred_at timestamptz not null default now(), acknowledged_by uuid references public.profiles(id), acknowledged_at timestamptz, resolved_at timestamptz, response_id uuid, created_at timestamptz default now());
create table if not exists public.emergency_exits (id uuid primary key default gen_random_uuid(), exit_no text not null unique, name text not null, building text, floor text, location text, status text not null default 'normal' check(status in ('normal','blocked','locked','inspection_due','maintenance','offline')), last_inspection date, next_inspection date, notes text, created_by uuid references public.profiles(id), created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.assembly_points (id uuid primary key default gen_random_uuid(), point_no text not null unique, name text not null, location text, capacity integer, status text not null default 'available' check(status in ('available','unavailable','overcrowded')), notes text, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.emergency_responses (id uuid primary key default gen_random_uuid(), response_no text not null unique, response_type text not null, scenario text, location text, status text not null default 'active' check(status in ('active','missing','accounted','all_clear','closed','cancelled')), started_at timestamptz default now(), closed_at timestamptz, assembly_point_id uuid references public.assembly_points(id), coordinator text, notes text, created_by uuid references public.profiles(id), created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.emergency_timeline (id uuid primary key default gen_random_uuid(), response_id uuid not null references public.emergency_responses(id) on delete cascade, event_type text not null, event_time timestamptz default now(), actor_name text, details text, created_by uuid references public.profiles(id), created_at timestamptz default now());
create table if not exists public.emergency_muster (id uuid primary key default gen_random_uuid(), response_id uuid not null references public.emergency_responses(id) on delete cascade, person_type text not null check(person_type in ('employee','contractor','visitor')), person_id text, person_name text not null, company text, status text not null default 'missing' check(status in ('missing','accounted','exempt')), accounted_at timestamptz, accounted_by uuid references public.profiles(id), created_at timestamptz default now(), unique(response_id,person_type,person_id));
create table if not exists public.emergency_drills (id uuid primary key default gen_random_uuid(), drill_ref text not null unique, drill_type text not null, scenario text not null, factory text, location text, drill_date date not null, evacuation_minutes numeric, participants integer, assembly_point text, coordinator text, safety_officer text, assessment text, observations text, status text not null default 'planned' check(status in ('planned','in_progress','completed','cancelled')), created_by uuid references public.profiles(id), created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.fire_equipment (id uuid primary key default gen_random_uuid(), asset_no text not null unique, serial_no text, equipment_type text not null, category text, manufacturer text, model text, capacity text, building text, zone text, department text, status text not null default 'good' check(status in ('good','inspection_due','maintenance_due','damaged','out_of_service','expired')), last_inspection date, next_inspection date, qr_code text unique, notes text, created_by uuid references public.profiles(id), created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.safety_assets (id uuid primary key default gen_random_uuid(), asset_tag text not null unique, name text not null, category text not null, location text, factory text, department text, last_inspection date, next_due date, status text not null default 'active' check(status in ('active','inspection_due','maintenance','damaged','out_of_service','retired')), qr_code text unique, notes text, created_by uuid references public.profiles(id), created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.equipment_passports (id uuid primary key default gen_random_uuid(), asset_id uuid references public.safety_assets(id) on delete set null, equipment_no text not null unique, name text not null, equipment_type text, serial_no text, manufacturer text, model text, department text, factory text, area text, risk_rating text check(risk_rating in ('low','medium','high','critical')), certificate_no text, certificate_expiry date, next_inspection date, next_maintenance date, operator_authorization_required boolean default false, loto_required boolean default false, status text not null default 'active', notes text, created_by uuid references public.profiles(id), created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.safety_maps (id uuid primary key default gen_random_uuid(), name text not null, building text, floor text, image_url text, width numeric, height numeric, active boolean default true, created_by uuid references public.profiles(id), created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.safety_map_points (id uuid primary key default gen_random_uuid(), map_id uuid not null references public.safety_maps(id) on delete cascade, point_type text not null check(point_type in ('fire_device','emergency_exit','first_aid','spill_kit','equipment','high_risk_zone','custom')), label text not null, x numeric not null, y numeric not null, source_type text, source_id uuid, status text default 'normal', created_by uuid references public.profiles(id), created_at timestamptz default now());
create table if not exists public.contractors (id uuid primary key default gen_random_uuid(), registration_no text not null unique, name text not null, scope text, contact_name text, email text, phone text, contract_start date, contract_end date, insurance_expiry date, status text not null default 'pending' check(status in ('approved','conditional','pending','blocked','suspended','expired','rejected')), notes text, created_by uuid references public.profiles(id), created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.contractor_workers (id uuid primary key default gen_random_uuid(), contractor_id uuid not null references public.contractors(id) on delete cascade, full_name text not null, national_id text, job_title text, induction_status text default 'pending', medical_expiry date, competency_expiry date, status text default 'active', created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.contractor_documents (id uuid primary key default gen_random_uuid(), worker_id uuid references public.contractor_workers(id) on delete cascade, contractor_id uuid references public.contractors(id) on delete cascade, document_type text not null, certificate_no text, issue_date date, expiry_date date, critical_for_access boolean default false, file_url text, status text default 'valid', created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.visitors (id uuid primary key default gen_random_uuid(), badge_no text not null unique, visitor_name text not null, company text, national_id text, host text, induction_status text default 'pending' check(induction_status in ('pending','completed','expired')), check_in timestamptz, check_out timestamptz, status text default 'expected' check(status in ('expected','onsite','checked_out','blocked')), qr_code text unique, notes text, created_by uuid references public.profiles(id), created_at timestamptz default now(), updated_at timestamptz default now());
create index if not exists fire_devices_status_idx on public.fire_devices(status,next_inspection); create index if not exists fire_events_status_time_idx on public.fire_events(status,occurred_at desc); create index if not exists emergency_responses_status_idx on public.emergency_responses(status,started_at desc); create index if not exists emergency_muster_response_status_idx on public.emergency_muster(response_id,status); create index if not exists emergency_drills_date_status_idx on public.emergency_drills(drill_date desc,status); create index if not exists safety_assets_status_due_idx on public.safety_assets(status,next_due); create index if not exists contractor_status_idx on public.contractors(status,insurance_expiry); create index if not exists visitors_status_idx on public.visitors(status,check_in);
DO $$ DECLARE t text; BEGIN FOREACH t IN ARRAY ARRAY['fire_gateways','fire_panels','fire_devices','fire_events','emergency_exits','assembly_points','emergency_responses','emergency_timeline','emergency_muster','emergency_drills','fire_equipment','safety_assets','equipment_passports','safety_maps','safety_map_points','contractors','contractor_workers','contractor_documents','visitors'] LOOP EXECUTE format('alter table public.%I enable row level security',t); EXECUTE format('drop policy if exists %I_staff_all on public.%I',t,t); EXECUTE format('create policy %I_staff_all on public.%I for all to authenticated using (private.is_staff()) with check (private.is_staff())',t,t); EXECUTE format('grant select,insert,update,delete on public.%I to authenticated',t); EXECUTE format('revoke all on public.%I from anon',t); END LOOP; END $$;
