-- KSA SAFETY BOARD / Section 09 HSE Reports & Documents
insert into public.permissions(code,description) values
 ('documents.read','Read HSE documents'),('documents.manage','Manage HSE documents'),('safety_signs.manage','Manage safety signs'),('contracts.manage','Manage HSE contracts'),('forms.manage','Manage controlled forms'),('invoices.manage','Manage HSE invoices') on conflict (code) do nothing;
create table if not exists public.hse_documents (id uuid primary key default gen_random_uuid(), document_no text unique, title text not null, category text not null check(category in ('report','certificate','license','procedure','evidence','contract','form','invoice','other')), document_type text, status text not null default 'draft' check(status in ('draft','under_review','approved','expired','archived')), file_name text, mime_type text, file_size_bytes bigint, storage_bucket text, storage_path text, external_url text, source_type text, source_id uuid, revision text default '1.0', issued_at date, expiry_at date, created_by uuid references public.profiles(id), approved_by uuid references public.profiles(id), approved_at timestamptz, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.safety_signs (id uuid primary key default gen_random_uuid(), document_no text unique not null, title_en text not null, title_ar text, instructions_en text, instructions_ar text, category text not null check(category in ('fire_safety','ppe','electrical','machinery','traffic','chemical','general')), status text not null default 'draft' check(status in ('active','draft','under_review','expired','archived')), size text not null default 'a4_portrait' check(size in ('a4_portrait','a4_landscape','a3_portrait','a3_landscape','custom')), custom_width numeric, custom_height numeric, background_color text default '#ffffff', qr_target text, print_count integer not null default 0, logo_url text, created_by uuid references public.profiles(id), created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.hse_contracts (id uuid primary key default gen_random_uuid(), reference_no text unique not null, title text not null, vendor text, department text, start_date date, end_date date, contract_value numeric, currency text default 'SAR', status text not null default 'pending' check(status in ('active','expired','pending')), metadata jsonb not null default '{}'::jsonb, notes text, created_by uuid references public.profiles(id), created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.hse_forms (id uuid primary key default gen_random_uuid(), form_no text unique not null, title text not null, description text, status text not null default 'draft' check(status in ('active','draft','archived')), version text default '1.0', document_id uuid references public.hse_documents(id) on delete set null, attachment_url text, created_by uuid references public.profiles(id), created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.hse_invoices (id uuid primary key default gen_random_uuid(), invoice_no text unique not null, vendor text, department text, invoice_date date, due_date date, amount numeric, currency text default 'SAR', status text not null default 'unpaid' check(status in ('paid','unpaid','overdue')), document_id uuid references public.hse_documents(id) on delete set null, notes text, created_by uuid references public.profiles(id), created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.hse_report_exports (id uuid primary key default gen_random_uuid(), report_type text not null, source_type text, source_id uuid, title text not null, format text not null check(format in ('print','pdf','csv','json','doc')), parameters jsonb not null default '{}'::jsonb, generated_by uuid references public.profiles(id), generated_at timestamptz default now(), status text not null default 'generated' check(status in ('generated','failed','expired')), storage_bucket text, storage_path text);
create index if not exists hse_documents_category_status_idx on public.hse_documents(category,status,expiry_at); create index if not exists safety_signs_category_status_idx on public.safety_signs(category,status); create index if not exists hse_contracts_status_dates_idx on public.hse_contracts(status,end_date); create index if not exists hse_forms_status_idx on public.hse_forms(status); create index if not exists hse_invoices_status_due_idx on public.hse_invoices(status,due_date); create index if not exists hse_report_exports_type_date_idx on public.hse_report_exports(report_type,generated_at desc);
DO $$ DECLARE t text; BEGIN FOREACH t IN ARRAY ARRAY['hse_documents','safety_signs','hse_contracts','hse_forms','hse_invoices','hse_report_exports'] LOOP EXECUTE format('alter table public.%I enable row level security',t); EXECUTE format('drop policy if exists %I_staff_all on public.%I',t,t); EXECUTE format('create policy %I_staff_all on public.%I for all to authenticated using (private.is_staff()) with check (private.is_staff())',t,t); EXECUTE format('grant select,insert,update,delete on public.%I to authenticated',t); EXECUTE format('revoke all on public.%I from anon',t); END LOOP; END $$;
