-- KSA SAFETY BOARD / Section 10 Safety Communication & Culture
alter table public.departments add column if not exists reporting_department_id uuid references public.departments(id) on delete set null;
create index if not exists departments_reporting_idx on public.departments(reporting_department_id);

create table if not exists public.hse_posts (id uuid primary key default gen_random_uuid(), title text not null, body text not null, status text not null default 'draft' check(status in ('draft','published','archived')), audience text not null default 'staff' check(audience in ('staff','department','site','public')), department_id uuid references public.departments(id), published_at timestamptz, archived_at timestamptz, created_by uuid references public.profiles(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create index if not exists hse_posts_status_idx on public.hse_posts(status,published_at desc);

create table if not exists public.notification_rules (id uuid primary key default gen_random_uuid(), name text not null, event_type text not null, severity public.priority_level not null default 'medium', channel text not null default 'in_app' check(channel in ('in_app','email','whatsapp','teams')), recipient text not null, is_active boolean not null default true, created_by uuid references public.profiles(id), updated_by uuid references public.profiles(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(name,event_type));
create index if not exists notification_rules_active_idx on public.notification_rules(is_active,event_type);

create table if not exists public.gamification_points_ledger (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, points integer not null check(points <> 0), reason text not null, source_type text, source_id uuid, idempotency_key text unique, period text not null default to_char(now(),'YYYY-MM'), created_by uuid references public.profiles(id), created_at timestamptz not null default now());
create table if not exists public.gamification_badges (id uuid primary key default gen_random_uuid(), code text unique not null, name text not null, description text, criteria jsonb not null default '{}'::jsonb, is_active boolean not null default true, created_at timestamptz not null default now());
create table if not exists public.gamification_awards (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, badge_id uuid not null references public.gamification_badges(id) on delete cascade, awarded_at timestamptz not null default now(), source_type text, source_id uuid, unique(user_id,badge_id));
create index if not exists gamification_points_user_idx on public.gamification_points_ledger(user_id,period,created_at desc);

create table if not exists public.safety_radio_channels (id uuid primary key default gen_random_uuid(), name text not null, channel_type text not null default 'general' check(channel_type in ('general','private','emergency_public')), is_active boolean not null default true, created_by uuid references public.profiles(id), created_at timestamptz not null default now());
create table if not exists public.safety_radio_members (channel_id uuid not null references public.safety_radio_channels(id) on delete cascade, user_id uuid not null references public.profiles(id) on delete cascade, added_by uuid references public.profiles(id), created_at timestamptz not null default now(), primary key(channel_id,user_id));
create table if not exists public.safety_radio_floor_leases (channel_id uuid primary key references public.safety_radio_channels(id) on delete cascade, holder_id uuid not null references public.profiles(id) on delete cascade, acquired_at timestamptz not null default now(), expires_at timestamptz not null, heartbeat_at timestamptz not null default now());
create index if not exists safety_radio_floor_expiry_idx on public.safety_radio_floor_leases(expires_at);

insert into public.permissions(code,description) values
 ('champions.read','View Safety Champions'),('champions.manage','Manage Safety Champions'),('departments.read','View Departments'),('departments.manage','Manage Departments'),('posts.read','View Safety Communications'),('posts.manage','Manage Safety Communications'),('radio.read','Use Safety Radio'),('radio.manage','Manage Safety Radio'),('inbox.read','View HSE Inbox'),('inbox.manage','Manage HSE Inbox'),('notification_rules.read','View HSE Alert Rules'),('notification_rules.manage','Manage HSE Alert Rules'),('email_settings.read','View email provider readiness') on conflict(code) do nothing;

DO $$ DECLARE t text; BEGIN FOREACH t IN ARRAY ARRAY['hse_posts','notification_rules','gamification_points_ledger','gamification_badges','gamification_awards','safety_radio_channels','safety_radio_members','safety_radio_floor_leases'] LOOP EXECUTE format('alter table public.%I enable row level security',t); EXECUTE format('drop policy if exists %I_staff_all on public.%I',t,t); EXECUTE format('create policy %I_staff_all on public.%I for all to authenticated using (private.is_staff()) with check (private.is_staff())',t,t); EXECUTE format('grant select,insert,update,delete on public.%I to authenticated',t); EXECUTE format('revoke all on public.%I from anon',t); END LOOP; END $$;
create policy staff_departments_delete on public.departments for delete to authenticated using (private.is_staff());
create policy staff_notifications_delete on public.notifications for delete to authenticated using (private.is_staff() or recipient_id = auth.uid());

create or replace function public.radio_acquire_floor(p_channel_id uuid, p_ttl_seconds integer default 30) returns public.safety_radio_floor_leases language plpgsql security invoker set search_path=public as $$ declare result public.safety_radio_floor_leases; begin if not exists(select 1 from safety_radio_channels c left join safety_radio_members m on m.channel_id=c.id and m.user_id=auth.uid() where c.id=p_channel_id and c.is_active and (c.channel_type <> 'private' or m.user_id is not null)) then raise exception 'Radio channel access denied' using errcode='42501'; end if; delete from safety_radio_floor_leases where channel_id=p_channel_id and expires_at < now(); insert into safety_radio_floor_leases(channel_id,holder_id,expires_at) values(p_channel_id,auth.uid(),now()+make_interval(secs=>least(greatest(p_ttl_seconds,10),120))) returning * into result; return result; end $$;
create or replace function public.radio_heartbeat_floor(p_channel_id uuid,p_ttl_seconds integer default 30) returns public.safety_radio_floor_leases language plpgsql security invoker set search_path=public as $$ declare result public.safety_radio_floor_leases; begin update safety_radio_floor_leases set heartbeat_at=now(),expires_at=now()+make_interval(secs=>least(greatest(p_ttl_seconds,10),120)) where channel_id=p_channel_id and holder_id=auth.uid() and expires_at>=now() returning * into result; if result.channel_id is null then raise exception 'Floor lease is not held' using errcode='40900'; end if; return result; end $$;
create or replace function public.radio_release_floor(p_channel_id uuid) returns boolean language plpgsql security invoker set search_path=public as $$ begin delete from safety_radio_floor_leases where channel_id=p_channel_id and holder_id=auth.uid(); return found; end $$;
grant execute on function public.radio_acquire_floor(uuid,integer),public.radio_heartbeat_floor(uuid,integer),public.radio_release_floor(uuid) to authenticated;
